-- PostgreSQL schema for Advice Content Radar MVP
CREATE TABLE IF NOT EXISTS sources (id SERIAL PRIMARY KEY, name TEXT NOT NULL, platform TEXT NOT NULL, source_url TEXT NOT NULL UNIQUE, source_type TEXT NOT NULL, category TEXT, location TEXT, priority_score INT DEFAULT 50, active BOOLEAN DEFAULT TRUE, created_at TIMESTAMP DEFAULT NOW(), updated_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS posts (id SERIAL PRIMARY KEY, source_id INT REFERENCES sources(id), post_url TEXT UNIQUE NOT NULL, post_text TEXT, media_url TEXT, posted_at TIMESTAMP, collected_at TIMESTAMP DEFAULT NOW(), like_count INT DEFAULT 0, comment_count INT DEFAULT 0, share_count INT DEFAULT 0, view_count INT DEFAULT 0, raw_viral_score FLOAT DEFAULT 0, normalized_score FLOAT DEFAULT 0, local_relevance_score FLOAT DEFAULT 0, final_score FLOAT DEFAULT 0, detected_product_category TEXT, detected_content_type TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS analyses (id SERIAL PRIMARY KEY, post_id INT UNIQUE REFERENCES posts(id), hook TEXT, hook_type JSONB, content_type TEXT, pain_point TEXT, engagement_trigger JSONB, why_it_worked TEXT, risk JSONB, local_angle TEXT, suggested_hook TEXT, caption_draft TEXT, creative_direction TEXT, sales_bridge TEXT, cta TEXT, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS daily_reports (id SERIAL PRIMARY KEY, report_date DATE UNIQUE NOT NULL, summary TEXT, top_posts JSONB, recommended_actions JSONB, best_hooks JSONB, telegram_message TEXT, telegram_sent_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS saved_ideas (id SERIAL PRIMARY KEY, report_id INT REFERENCES daily_reports(id), post_id INT REFERENCES posts(id), idea_number INT, title TEXT, local_angle TEXT, suggested_hook TEXT, caption_draft TEXT, creative_direction TEXT, status TEXT DEFAULT 'saved', created_at TIMESTAMP DEFAULT NOW(), used_at TIMESTAMP, UNIQUE(report_id, idea_number));
CREATE TABLE IF NOT EXISTS content_memory (id SERIAL PRIMARY KEY, idea_text TEXT, hook TEXT, product_category TEXT, content_type TEXT, used BOOLEAN DEFAULT FALSE, used_at TIMESTAMP, created_at TIMESTAMP DEFAULT NOW());
CREATE TABLE IF NOT EXISTS job_runs (id SERIAL PRIMARY KEY, job_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'running', result JSONB, error TEXT, started_at TIMESTAMP DEFAULT NOW(), finished_at TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_posts_collected_at ON posts(collected_at);
CREATE INDEX IF NOT EXISTS idx_posts_final_score ON posts(final_score);
CREATE INDEX IF NOT EXISTS idx_reports_report_date ON daily_reports(report_date);
